<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class EmergencySeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $contacts = [
            // 1. Police & Emergency Response
            [
                'category_en'        => 'Police & Emergency',
                'category_ur'        => 'پولیس اور ہنگامی خدمات',
                'department_name_en' => 'Rescue 1122 Punjab (Emergency Response)',
                'department_name_ur' => 'ریسکیو 1122 پنجاب (ہنگامی امداد)',
                'phone_primary'      => '1122',
                'phone_secondary'    => '0606-920122',
                'email'              => 'info@rescue.gov.pk',
                'address_en'         => 'Rescue 1122 Station, Main Highway, Kot Sultan / Layyah',
                'address_ur'         => 'ریسکیو 1122 اسٹیشن، مین شاہراہ، کوٹ سلطان / لیہ',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://rescue.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Rescue+1122+Layyah',
                'latitude'           => '30.9634',
                'longitude'          => '70.9392',
                'icon'               => 'ambulance',
                'display_order'      => 1,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Police & Emergency',
                'category_ur'        => 'پولیس اور ہنگامی خدمات',
                'department_name_en' => 'Punjab Police Emergency Helpline',
                'department_name_ur' => 'پنجاب پولیس ایمرجنسی ہیلپ لائن',
                'phone_primary'      => '15',
                'phone_secondary'    => '0800-15150',
                'email'              => 'feedback@punjabpolice.gov.pk',
                'address_en'         => 'Central Police Control Room, Layyah',
                'address_ur'         => 'مرکزی پولیس کنٹرول روم، لیہ',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://punjabpolice.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=District+Police+Office+Layyah',
                'latitude'           => '30.9600',
                'longitude'          => '70.9400',
                'icon'               => 'shield-alert',
                'display_order'      => 2,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Police & Emergency',
                'category_ur'        => 'پولیس اور ہنگامی خدمات',
                'department_name_en' => 'Police Station Kot Sultan (تھانہ کوٹ سلطان)',
                'department_name_ur' => 'تھانہ کوٹ سلطان (پنجاب پولیس)',
                'phone_primary'      => '068-5544100',
                'phone_secondary'    => '0307-7798369',
                'email'              => 'dpo.layyah@punjabpolice.gov.pk',
                'address_en'         => 'Police Station Road, Kot Sultan, District Layyah',
                'address_ur'         => 'تھانہ روڈ، کوٹ سلطان، ضلع لیہ',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://punjabpolice.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Police+Station+Kot+Sultan',
                'latitude'           => '30.7720',
                'longitude'          => '70.8530',
                'icon'               => 'shield',
                'display_order'      => 3,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Police & Emergency',
                'category_ur'        => 'پولیس اور ہنگامی خدمات',
                'department_name_en' => 'Punjab Highway Patrol (PHP)',
                'department_name_ur' => 'پنجاب ہائی وے پٹرول (پی ایچ پی)',
                'phone_primary'      => '1124',
                'phone_secondary'    => '0606-920155',
                'email'              => 'php@punjabpolice.gov.pk',
                'address_en'         => 'PHP Post, MM Road Kot Sultan, Layyah',
                'address_ur'         => 'پی ایچ پی پوسٹ، ایم ایم روڈ کوٹ سلطان، لیہ',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://punjabpolice.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Punjab+Highway+Patrol+Kot+Sultan',
                'latitude'           => '30.7750',
                'longitude'          => '70.8500',
                'icon'               => 'car-taxi-front',
                'display_order'      => 4,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Police & Emergency',
                'category_ur'        => 'پولیس اور ہنگامی خدمات',
                'department_name_en' => 'National Highways & Motorway Police',
                'department_name_ur' => 'نیشنل ہائی ویز اینڈ موٹروے پولیس',
                'phone_primary'      => '130',
                'phone_secondary'    => '051-9250500',
                'email'              => 'info@nhmp.gov.pk',
                'address_en'         => 'Sector Command N-55, Punjab Region',
                'address_ur'         => 'سیکٹر کمانڈ این-55، پنجاب ریجن',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://nhmp.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Motorway+Police+Control+Room',
                'latitude'           => '30.9000',
                'longitude'          => '70.9000',
                'icon'               => 'siren',
                'display_order'      => 5,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // 2. Medical & Health Services
            [
                'category_en'        => 'Medical & Health',
                'category_ur'        => 'طبی و صحت و ہسپتال',
                'department_name_en' => 'THQ Hospital Kot Sultan',
                'department_name_ur' => 'تحصیل ہیڈ کوارٹر ہسپتال کوٹ سلطان',
                'phone_primary'      => '068-5544200',
                'phone_secondary'    => '0300-6781122',
                'email'              => 'ms.thq.kotsultan@punjab.gov.pk',
                'address_en'         => 'Hospital Road, Near Railway Station, Kot Sultan',
                'address_ur'         => 'ہسپتال روڈ، نزد ریلوے اسٹیشن، کوٹ سلطان',
                'working_hours_en'   => 'Emergency: 24/7 | OPD: 8:00 AM - 2:00 PM',
                'working_hours_ur'   => 'ایمرجنسی: 24 گھنٹے | او پی ڈی: صبح 8 تا دوپہر 2 بجے',
                'website'            => 'https://health.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=THQ+Hospital+Kot+Sultan',
                'latitude'           => '30.7710',
                'longitude'          => '70.8540',
                'icon'               => 'hospital',
                'display_order'      => 6,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Medical & Health',
                'category_ur'        => 'طبی و صحت و ہسپتال',
                'department_name_en' => 'DHQ Hospital Layyah (Emergency & Trauma)',
                'department_name_ur' => 'ڈسٹرکٹ ہیڈ کوارٹر ہسپتال لیہ',
                'phone_primary'      => '0606-920150',
                'phone_secondary'    => '0606-920151',
                'email'              => 'dhq.layyah@punjab.gov.pk',
                'address_en'         => 'College Road, Civil Lines, Layyah',
                'address_ur'         => 'کالج روڈ، سول لائنز، لیہ',
                'working_hours_en'   => '24 Hours Emergency Services',
                'working_hours_ur'   => '24 گھنٹے ہنگامی طبی خدمات',
                'website'            => 'https://dhqlayyah.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=DHQ+Hospital+Layyah',
                'latitude'           => '30.9650',
                'longitude'          => '70.9380',
                'icon'               => 'cross',
                'display_order'      => 7,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Medical & Health',
                'category_ur'        => 'طبی و صحت و ہسپتال',
                'department_name_en' => 'Edhi Emergency Ambulance Service',
                'department_name_ur' => 'ایدھی ایمرجنسی ایمبولینس سروس',
                'phone_primary'      => '115',
                'phone_secondary'    => '0606-920115',
                'email'              => 'info@edhi.org',
                'address_en'         => 'Edhi Center, Main Multan Road, Layyah / Kot Sultan',
                'address_ur'         => 'ایدھی سینٹر، مین ملتان روڈ، لیہ / کوٹ سلطان',
                'working_hours_en'   => '24 Hours / 7 Days',
                'working_hours_ur'   => '24 گھنٹے / 7 ایام',
                'website'            => 'https://edhi.org',
                'google_maps'        => 'https://maps.google.com/?q=Edhi+Center+Layyah',
                'latitude'           => '30.9610',
                'longitude'          => '70.9390',
                'icon'               => 'heart-pulse',
                'display_order'      => 8,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Medical & Health',
                'category_ur'        => 'طبی و صحت و ہسپتال',
                'department_name_en' => 'Red Crescent Ambulance (ہلال احمر)',
                'department_name_ur' => 'پاکستان ہلال احمر ایمبولینس سروس',
                'phone_primary'      => '1030',
                'phone_secondary'    => '051-9250404',
                'email'              => 'info@prcs.org.pk',
                'address_en'         => 'Red Crescent Regional Office, Punjab',
                'address_ur'         => 'ہلال احمر ریجنل آفس، پنجاب',
                'working_hours_en'   => '24 Hours Emergency Response',
                'working_hours_ur'   => '24 گھنٹے ہنگامی رسپانس',
                'website'            => 'https://prcs.org.pk',
                'google_maps'        => 'https://maps.google.com/?q=Red+Crescent+Punjab',
                'latitude'           => '31.5204',
                'longitude'          => '74.3587',
                'icon'               => 'activity',
                'display_order'      => 9,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // 3. Utilities & Municipal Complaints
            [
                'category_en'        => 'Utilities & Public Services',
                'category_ur'        => 'افادیت و بجلی گیس پانی',
                'department_name_en' => 'MEPCO WAPDA Electricity (Kot Sultan Sub-Division)',
                'department_name_ur' => 'میپکو واپڈا بجلی شکایت (کوٹ سلطان سب ڈویژن)',
                'phone_primary'      => '118',
                'phone_secondary'    => '068-5544300',
                'email'              => 'complaints@mepco.com.pk',
                'address_en'         => 'MEPCO Sub-Division Office, Grid Station Road, Kot Sultan',
                'address_ur'         => 'میپکو سب ڈویژن آفس، گرڈ اسٹیشن روڈ، کوٹ سلطان',
                'working_hours_en'   => '24/7 Complaint Center',
                'working_hours_ur'   => '24 گھنٹے شکایات سیل',
                'website'            => 'https://mepco.com.pk',
                'google_maps'        => 'https://maps.google.com/?q=MEPCO+Substation+Kot+Sultan',
                'latitude'           => '30.7730',
                'longitude'          => '70.8510',
                'icon'               => 'zap',
                'display_order'      => 10,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Utilities & Public Services',
                'category_ur'        => 'افادیت و بجلی گیس پانی',
                'department_name_en' => 'SNGPL Sui Gas Emergency Helpline',
                'department_name_ur' => 'سوئی ناردرن گیس ایمرجنسی ہیلپ لائن (SNGPL)',
                'phone_primary'      => '1199',
                'phone_secondary'    => '0606-920199',
                'email'              => 'customercare@sngpl.com.pk',
                'address_en'         => 'SNGPL Regional Office, Layyah / Kot Sultan',
                'address_ur'         => 'ایس این جی پی ایل ریجنل آفس، لیہ / کوٹ سلطان',
                'working_hours_en'   => '24 Hours Gas Leakage Emergency',
                'working_hours_ur'   => '24 گھنٹے گیس لیکج ایمرجنسی',
                'website'            => 'https://sngpl.com.pk',
                'google_maps'        => 'https://maps.google.com/?q=SNGPL+Office+Layyah',
                'latitude'           => '30.9620',
                'longitude'          => '70.9370',
                'icon'               => 'flame',
                'display_order'      => 11,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Utilities & Public Services',
                'category_ur'        => 'افادیت و بجلی گیس پانی',
                'department_name_en' => 'PTCL Broadband & Telephone Complaints',
                'department_name_ur' => 'پی ٹی سی ایل ٹیلی فون و انٹرنیٹ شکایت',
                'phone_primary'      => '1218',
                'phone_secondary'    => '1217',
                'email'              => 'care@ptcl.net.pk',
                'address_en'         => 'PTCL Exchange, Railway Road, Kot Sultan',
                'address_ur'         => 'پی ٹی سی ایل ایکسچینج، ریلوے روڈ، کوٹ سلطان',
                'working_hours_en'   => '8:00 AM - 8:00 PM',
                'working_hours_ur'   => 'صبح 8 تا رات 8 بجے',
                'website'            => 'https://ptcl.com.pk',
                'google_maps'        => 'https://maps.google.com/?q=PTCL+Exchange+Kot+Sultan',
                'latitude'           => '30.7740',
                'longitude'          => '70.8520',
                'icon'               => 'phone',
                'display_order'      => 12,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // 4. Government & Local Administration
            [
                'category_en'        => 'Government Administration',
                'category_ur'        => 'حکومتی و انتظامی دفاتر',
                'department_name_en' => 'Assistant Commissioner Office (AC Kot Sultan/Layyah)',
                'department_name_ur' => 'دفتر اسسٹنٹ کمشنر (لیہ / کوٹ سلطان)',
                'phone_primary'      => '0606-920108',
                'phone_secondary'    => '0606-920109',
                'email'              => 'ac.layyah@punjab.gov.pk',
                'address_en'         => 'Kutchery Road, District Complex, Layyah',
                'address_ur'         => 'کچہری روڈ، ڈسٹرکٹ کمپلیکس، لیہ',
                'working_hours_en'   => 'Mon - Fri: 8:00 AM - 4:00 PM',
                'working_hours_ur'   => 'پیر تا جمعہ: صبح 8 تا شام 4 بجے',
                'website'            => 'https://layyah.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Assistant+Commissioner+Office+Layyah',
                'latitude'           => '30.9640',
                'longitude'          => '70.9360',
                'icon'               => 'building-2',
                'display_order'      => 13,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Government Administration',
                'category_ur'        => 'حکومتی و انتظامی دفاتر',
                'department_name_en' => 'Deputy Commissioner Office Layyah (DC Office)',
                'department_name_ur' => 'دفتر ڈپٹی کمشنر لیہ (ڈی سی آفس)',
                'phone_primary'      => '0606-920100',
                'phone_secondary'    => '0606-920101',
                'email'              => 'dc.layyah@punjab.gov.pk',
                'address_en'         => 'District Complex, Civil Lines, Layyah',
                'address_ur'         => 'ڈسٹرکٹ کمپلیکس، سول لائنز، لیہ',
                'working_hours_en'   => 'Mon - Fri: 8:00 AM - 4:00 PM',
                'working_hours_ur'   => 'پیر تا جمعہ: صبح 8 تا شام 4 بجے',
                'website'            => 'https://layyah.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=DC+Office+Layyah',
                'latitude'           => '30.9645',
                'longitude'          => '70.9365',
                'icon'               => 'landmark',
                'display_order'      => 14,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Government Administration',
                'category_ur'        => 'حکومتی و انتظامی دفاتر',
                'department_name_en' => 'Municipal Committee Kot Sultan',
                'department_name_ur' => 'میونسپل کمیٹی کوٹ سلطان',
                'phone_primary'      => '068-5544050',
                'phone_secondary'    => '068-5544051',
                'email'              => 'mc.kotsultan@lgcd.punjab.gov.pk',
                'address_en'         => 'MC Building, Main Bazaar, Kot Sultan',
                'address_ur'         => 'میونسپل کمیٹی بلڈنگ، مین بازار، کوٹ سلطان',
                'working_hours_en'   => 'Mon - Sat: 9:00 AM - 3:00 PM',
                'working_hours_ur'   => 'پیر تا ہفتہ: صبح 9 تا دوپہر 3 بجے',
                'website'            => 'https://lgcd.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Municipal+Committee+Kot+Sultan',
                'latitude'           => '30.7728',
                'longitude'          => '70.8528',
                'icon'               => 'building',
                'display_order'      => 15,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Government Administration',
                'category_ur'        => 'حکومتی و انتظامی دفاتر',
                'department_name_en' => 'NADRA Registration Center Kot Sultan / Layyah',
                'department_name_ur' => 'نادرا رجسٹریشن سینٹر کوٹ سلطان / لیہ',
                'phone_primary'      => '1777',
                'phone_secondary'    => '051-111-786-100',
                'email'              => 'helpline@nadra.gov.pk',
                'address_en'         => 'NADRA Office, Station Road, Kot Sultan',
                'address_ur'         => 'نادرا آفس، اسٹیشن روڈ، کوٹ سلطان',
                'working_hours_en'   => 'Mon - Fri: 8:00 AM - 4:00 PM',
                'working_hours_ur'   => 'پیر تا جمعہ: صبح 8 تا شام 4 بجے',
                'website'            => 'https://nadra.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=NADRA+Executive+Office+Layyah',
                'latitude'           => '30.7715',
                'longitude'          => '70.8515',
                'icon'               => 'id-card',
                'display_order'      => 16,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // 5. Protection, Social Welfare & Helplines
            [
                'category_en'        => 'Protection & Social Helpline',
                'category_ur'        => 'تحفظ خواتین و اطفال ہیلپ لائن',
                'department_name_en' => 'Punjab Women Safety & Protection Helpline',
                'department_name_ur' => 'پنجاب وومن سیفٹی و تحفظ خواتین ہیلپ لائن',
                'phone_primary'      => '1043',
                'phone_secondary'    => '042-99204158',
                'email'              => 'pcsw@punjab.gov.pk',
                'address_en'         => 'Punjab Commission on the Status of Women, Lahore',
                'address_ur'         => 'پنجاب کمیشن آن دی سٹیٹس آف وومن، لاہور',
                'working_hours_en'   => '24 Hours / 7 Days Toll-Free',
                'working_hours_ur'   => '24 گھنٹے ٹول فری سروس',
                'website'            => 'https://pcsw.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=PCSW+Lahore',
                'latitude'           => '31.5500',
                'longitude'          => '74.3400',
                'icon'               => 'heart-handshake',
                'display_order'      => 17,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Protection & Social Helpline',
                'category_ur'        => 'تحفظ خواتین و اطفال ہیلپ لائن',
                'department_name_en' => 'Child Protection & Welfare Bureau Helpline',
                'department_name_ur' => 'چائلڈ پروٹیکشن اینڈ ویلفیئر بیورو ہیلپ لائن',
                'phone_primary'      => '1121',
                'phone_secondary'    => '042-99231700',
                'email'              => 'cpwb@punjab.gov.pk',
                'address_en'         => 'Child Protection Regional Bureau, Multan / Layyah',
                'address_ur'         => 'چائلڈ پروٹیکشن ریجنل بیورو، ملتان / لیہ',
                'working_hours_en'   => '24 Hours Toll-Free Helpline',
                'working_hours_ur'   => '24 گھنٹے مفت ہیلپ لائن',
                'website'            => 'https://cpwb.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Child+Protection+Bureau',
                'latitude'           => '30.1978',
                'longitude'          => '71.4697',
                'icon'               => 'baby',
                'display_order'      => 18,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Protection & Social Helpline',
                'category_ur'        => 'تحفظ خواتین و اطفال ہیلپ لائن',
                'department_name_en' => 'Punjab Citizen Portal & Govt Helpline',
                'department_name_ur' => 'پنجاب سٹیزن پورٹل اور شکایت سیل',
                'phone_primary'      => '0800-02345',
                'phone_secondary'    => '042-99030000',
                'email'              => 'info@pitb.gov.pk',
                'address_en'         => 'Arfa Software Technology Park, Lahore',
                'address_ur'         => 'عارفہ سافٹ ویئر ٹیکنالوجی پارک، لاہور',
                'working_hours_en'   => 'Mon - Sat: 9:00 AM - 5:00 PM',
                'working_hours_ur'   => 'پیر تا ہفتہ: صبح 9 تا شام 5 بجے',
                'website'            => 'https://citizenportal.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=PITB+Lahore',
                'latitude'           => '31.4750',
                'longitude'          => '74.3430',
                'icon'               => 'user-check',
                'display_order'      => 19,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // 6. Agriculture & Livestock
            [
                'category_en'        => 'Agriculture & Livestock',
                'category_ur'        => 'زراعت اور لائیو سٹاک',
                'department_name_en' => 'Punjab Agriculture Department Helpline',
                'department_name_ur' => 'پنجاب محکمہ زراعت کسان ہیلپ لائن',
                'phone_primary'      => '0800-15000',
                'phone_secondary'    => '0800-29000',
                'email'              => 'info@agripunjab.gov.pk',
                'address_en'         => 'Agriculture Extension Office, Layyah / Kot Sultan',
                'address_ur'         => 'محکمہ توسیع زراعت، لیہ / کوٹ سلطان',
                'working_hours_en'   => 'Mon - Fri: 9:00 AM - 5:00 PM',
                'working_hours_ur'   => 'پیر تا جمعہ: صبح 9 تا شام 5 بجے',
                'website'            => 'https://agripunjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Agriculture+Office+Layyah',
                'latitude'           => '30.9630',
                'longitude'          => '70.9350',
                'icon'               => 'sprout',
                'display_order'      => 20,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'category_en'        => 'Agriculture & Livestock',
                'category_ur'        => 'زراعت اور لائیو سٹاک',
                'department_name_en' => 'Veterinary Hospital & Livestock Helpline Kot Sultan',
                'department_name_ur' => 'سول ویٹرنری ہسپتال و لائیو سٹاک کوٹ سلطان',
                'phone_primary'      => '0800-78685',
                'phone_secondary'    => '068-5544090',
                'email'              => 'livestock@punjab.gov.pk',
                'address_en'         => 'Civil Veterinary Hospital, Hospital Road, Kot Sultan',
                'address_ur'         => 'سول ویٹرنری ہسپتال، ہسپتال روڈ، کوٹ سلطان',
                'working_hours_en'   => 'Mon - Sat: 8:00 AM - 2:00 PM',
                'working_hours_ur'   => 'پیر تا ہفتہ: صبح 8 تا دوپہر 2 بجے',
                'website'            => 'https://livestock.punjab.gov.pk',
                'google_maps'        => 'https://maps.google.com/?q=Veterinary+Hospital+Kot+Sultan',
                'latitude'           => '30.7718',
                'longitude'          => '70.8535',
                'icon'               => 'dog',
                'display_order'      => 21,
                'status'             => 'active',
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        $this->db->table('emergency_contacts')->insertBatch($contacts);
    }
}
